
use ventas3;
SELECT * FROM FAC_CABE;
USE VENTAS3;
CREATE PROCEDURE SPMES(AN INT)
SELECT MONTH(FAC_FEC) MES, COUNT(*) CANTIDAD, SUM(ART_PRE*ART_CAN) TOTAL
FROM FAC_CABE F, FAC_DETA D, ARTICULOS A
WHERE F.fac_num=D.fac_num AND D.art_cod=A.art_cod AND YEAR(FAC_FEC)=AN
GROUP BY MONTH(FAC_FEC);
